name: ✨ Feature Request
description: Suggest a new feature
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: ["pv-udpv"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like
      placeholder: What should this feature do?
    validations:
      required: true
  
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
      placeholder: What problem does it solve?
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: What alternatives have you considered?
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots